CREATE TABLE IF NOT EXISTS HOUSES_PARAMS<?= $suffix ?>
(
REGION BIGINT,
ID BIGINT,
OBJECTID BIGINT,
CHANGEID BIGINT,
CHANGEIDEND BIGINT,
TYPEID BIGINT,
VALUE TEXT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE
);

/*CREATE UNIQUE INDEX HOUSES_PARAMS<?= $suffix ?>_REGION_ID_ux
ON HOUSES_PARAMS<?= $suffix ?> (REGION,ID);*/

ALTER TABLE HOUSES_PARAMS
ATTACH PARTITION HOUSES_PARAMS<?= $suffix ?> FOR
VALUES IN (<?= $suffix ?>);