CREATE TABLE IF NOT EXISTS NORMDOCS
(
REGION BIGINT,
ID BIGINT,
NAME TEXT,
DATE DATE,
NUMBER TEXT,
TYPE BIGINT,
KIND BIGINT,
UPDATEDATE DATE,
ORGNAME TEXT,
REGNUM TEXT,
REGDATE DATE,
ACCDATE DATE,
COMMENT TEXT
)
PARTITION BY LIST (REGION);

/*CREATE UNIQUE INDEX NORMDOCS_REGION_ID_ux
ON NORMDOCS (REGION,ID);*/