CREATE TABLE IF NOT EXISTS ADDHOUSETYPES
(
ID BIGINT,
NAME TEXT,
SHORTNAME TEXT,
DESCR TEXT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTIVE BIGINT
);

/*CREATE UNIQUE INDEX ADDHOUSETYPES_ID_ux
ON ADDHOUSETYPES (ID);*/