CREATE TABLE IF NOT EXISTS STEADS_PARAMS<?= $suffix ?>
(
REGION BIGINT,
ID BIGINT,
OBJECTID BIGINT,
CHANGEID BIGINT,
CHANGEIDEND BIGINT,
TYPEID BIGINT,
VALUE TEXT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE
);

/*CREATE UNIQUE INDEX STEADS_PARAMS<?= $suffix ?>_REGION_ID_ux
ON STEADS_PARAMS<?= $suffix ?> (REGION,ID);*/

ALTER TABLE STEADS_PARAMS
ATTACH PARTITION STEADS_PARAMS<?= $suffix ?> FOR
VALUES IN (<?= $suffix ?>);