CREATE TABLE IF NOT EXISTS APARTMENTTYPES
(
ID BIGINT,
NAME TEXT,
SHORTNAME TEXT,
DESCR TEXT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTIVE BIGINT
);

/*CREATE UNIQUE INDEX APARTMENTTYPES_ID_ux
ON APARTMENTTYPES (ID);*/