CREATE TABLE IF NOT EXISTS ADM_HIERARCHY
(
REGION BIGINT,
ID BIGINT,
OBJECTID BIGINT,
PARENTOBJID BIGINT,
CHANGEID BIGINT,
REGIONCODE TEXT,
AREACODE TEXT,
CITYCODE TEXT,
PLACECODE TEXT,
PLANCODE TEXT,
STREETCODE TEXT,
PREVID BIGINT,
NEXTID BIGINT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTIVE BIGINT,
PATH TEXT
)
PARTITION BY LIST (REGION);

/*CREATE UNIQUE INDEX ADM_HIERARCHY_REGION_ID_ux
ON ADM_HIERARCHY (REGION,ID);*/
