CREATE TABLE IF NOT EXISTS ADM_HIERARCHY<?= $suffix ?>
(
REGION BIGINT,
ID BIGINT,
OBJECTID BIGINT,
PARENTOBJID BIGINT,
CHANGEID BIGINT,
REGIONCODE TEXT,
AREACODE TEXT,
CITYCODE TEXT,
PLACECODE TEXT,
PLANCODE TEXT,
STREETCODE TEXT,
PREVID BIGINT,
NEXTID BIGINT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTIVE BIGINT,
PATH TEXT
);

/*CREATE UNIQUE INDEX ADM_HIERARCHY<?= $suffix ?>_REGION_ID_ux
ON ADM_HIERARCHY (REGION,ID);*/

ALTER TABLE ADM_HIERARCHY
ATTACH PARTITION ADM_HIERARCHY<?= $suffix ?> FOR
VALUES IN (<?= $suffix ?>);