CREATE TABLE IF NOT EXISTS APARTMENTS
(
REGION BIGINT,
ID BIGINT,
OBJECTID BIGINT,
OBJECTGUID TEXT,
NUMBER TEXT,
APARTTYPE BIGINT,
OPERTYPEID BIGINT,
PREVID BIGINT,
NEXTID BIGINT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTUAL BIGINT,
ISACTIVE BIGINT
)
PARTITION BY LIST (REGION);

/*CREATE UNIQUE INDEX APARTMENTS_REGION_ID_ux
ON APARTMENTS (REGION,ID);*/