CREATE TABLE IF NOT EXISTS OBJECTLEVELS
(
LEVEL BIGINT,
NAME TEXT,
SHORTNAME TEXT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTIVE BIGINT
);

/*CREATE UNIQUE INDEX OBJECTLEVELS_LEVEL_ux
ON OBJECTLEVELS (LEVEL);*/