CREATE TABLE IF NOT EXISTS ADDR_OBJ_DIVISION<?= $suffix ?>
(
REGION BIGINT,
ID BIGINT,
PARENTID BIGINT,
CHILDID BIGINT,
CHANGEID BIGINT
);

ALTER TABLE ADDR_OBJ_DIVISION
ATTACH PARTITION ADDR_OBJ_DIVISION<?= $suffix ?> FOR
VALUES IN (<?= $suffix ?>);