CREATE TABLE IF NOT EXISTS REESTR_OBJECTS<?= $suffix ?>
(
REGION BIGINT,
OBJECTID BIGINT,
OBJECTGUID TEXT,
CREATEDATE DATE,
CHANGEID BIGINT,
LEVELID BIGINT,
UPDATEDATE DATE,
ISACTIVE BIGINT
);

/*CREATE UNIQUE INDEX REESTR_OBJECTS<?= $suffix ?>_REGION_OBJECTID_ux
ON REESTR_OBJECTS<?= $suffix ?> (REGION,OBJECTID);*/

ALTER TABLE REESTR_OBJECTS
ATTACH PARTITION REESTR_OBJECTS<?= $suffix ?> FOR
VALUES IN (<?= $suffix ?>);