CREATE TABLE IF NOT EXISTS REESTR_OBJECTS
(
REGION BIGINT,
OBJECTID BIGINT,
OBJECTGUID TEXT,
CREATEDATE DATE,
CHANGEID BIGINT,
LEVELID BIGINT,
UPDATEDATE DATE,
ISACTIVE BIGINT
)
PARTITION BY LIST (REGION);

/*CREATE UNIQUE INDEX REESTR_OBJECTS_REGION_OBJECTID_ux
ON REESTR_OBJECTS (REGION,OBJECTID);*/