CREATE TABLE IF NOT EXISTS ROOMS
(
REGION BIGINT,
ID BIGINT,
OBJECTID BIGINT,
OBJECTGUID TEXT,
CHANGEID BIGINT,
NUMBER TEXT,
ROOMTYPE BIGINT,
OPERTYPEID BIGINT,
PREVID BIGINT,
NEXTID BIGINT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTUAL BIGINT,
ISACTIVE BIGINT
)
PARTITION BY LIST (REGION);

/*CREATE UNIQUE INDEX ROOMS_REGION_ID_ux
ON ROOMS (REGION,ID);*/