CREATE TABLE IF NOT EXISTS ROOMS<?= $suffix ?>
(
REGION BIGINT,
ID BIGINT,
OBJECTID BIGINT,
OBJECTGUID TEXT,
CHANGEID BIGINT,
NUMBER TEXT,
ROOMTYPE BIGINT,
OPERTYPEID BIGINT,
PREVID BIGINT,
NEXTID BIGINT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTUAL BIGINT,
ISACTIVE BIGINT
);

/*CREATE UNIQUE INDEX ROOMS<?= $suffix ?>_REGION_ID_ux
ON ROOMS<?= $suffix ?> (REGION,ID);*/

ALTER TABLE ROOMS
ATTACH PARTITION ROOMS<?= $suffix ?> FOR VALUES IN (<?= $suffix ?>);