CREATE TABLE IF NOT EXISTS PARAMTYPES
(
ID BIGINT,
NAME TEXT,
CODE TEXT,
DESCR TEXT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTIVE BIGINT
);

/*CREATE UNIQUE INDEX PARAMTYPES_ID_ux
ON PARAMTYPES (ID);*/