CREATE TABLE IF NOT EXISTS ADDRESSOBJECTS<?= $suffix ?>
(
REGION BIGINT,
ID BIGINT,
OBJECTID BIGINT,
OBJECTGUID TEXT,
CHANGEID BIGINT,
NAME TEXT,
TYPENAME TEXT,
LEVEL BIGINT,
OPERTYPEID BIGINT,
PREVID BIGINT,
NEXTID BIGINT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTUAL BIGINT,
ISACTIVE BIGINT
);

/*CREATE UNIQUE INDEX ADDRESSOBJECTS<?= $suffix ?>_REGION_ID_ux
ON ADDRESSOBJECTS<?= $suffix ?> (REGION,ID);*/

ALTER TABLE ADDRESSOBJECTS
ATTACH PARTITION ADDRESSOBJECTS<?= $suffix ?> FOR
VALUES IN (<?= $suffix ?>);