CREATE TABLE IF NOT EXISTS CHANGE_HISTORY
(
REGION BIGINT,
CHANGEID BIGINT,
OBJECTID BIGINT,
ADROBJECTID TEXT,
OPERTYPEID BIGINT,
NDOCID BIGINT,
CHANGEDATE DATE
)
PARTITION BY LIST (REGION);

/*CREATE UNIQUE INDEX CHANGE_HISTORY_REGION_CHANGEID_ux
ON CHANGE_HISTORY (REGION,CHANGEID);*/