CREATE TABLE IF NOT EXISTS CHANGE_HISTORY<?= $suffix ?>
(
REGION BIGINT,
CHANGEID BIGINT,
OBJECTID BIGINT,
ADROBJECTID TEXT,
OPERTYPEID BIGINT,
NDOCID BIGINT,
CHANGEDATE DATE
);

/*CREATE UNIQUE INDEX CHANGE_HISTORY<?= $suffix ?>_REGION_CHANGEID_ux
ON CHANGE_HISTORY<?= $suffix ?> (REGION,CHANGEID);*/

ALTER TABLE CHANGE_HISTORY
ATTACH PARTITION CHANGE_HISTORY<?= $suffix ?> FOR
VALUES IN (<?= $suffix ?>);