CREATE TABLE IF NOT EXISTS ADDRESSOBJECTTYPES
(
ID BIGINT,
LEVEL BIGINT,
SHORTNAME TEXT,
NAME TEXT,
DESCR TEXT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTIVE BIGINT
);

/*CREATE UNIQUE INDEX ADDRESSOBJECTTYPES_ID_ux
ON ADDRESSOBJECTTYPES (ID);*/
