CREATE INDEX MUN_HIERARCHY<?= $suffix ?>_REGION_OBJECTID_ISACTIVE_IX
ON MUN_HIERARCHY<?= $suffix ?> (REGION,OBJECTID,ISACTIVE);
CREATE INDEX MUN_HIERARCHY<?= $suffix ?>_REGION_PARENTOBJID_IX
ON MUN_HIERARCHY<?= $suffix ?> (REGION,PARENTOBJID);
