CREATE TABLE IF NOT EXISTS MUN_HIERARCHY
(
REGION BIGINT,
ID BIGINT,
OBJECTID BIGINT,
PARENTOBJID BIGINT,
CHANGEID BIGINT,
OKTMO TEXT,
PREVID BIGINT,
NEXTID BIGINT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTIVE BIGINT,
PATH TEXT
)
PARTITION BY LIST (REGION);

/*CREATE UNIQUE INDEX MUN_HIERARCHY_REGION_ID_ux
ON MUN_HIERARCHY (REGION,ID);*/