CREATE TABLE IF NOT EXISTS HOUSES
(
REGION BIGINT,
ID BIGINT,
OBJECTID BIGINT,
OBJECTGUID TEXT,
CHANGEID BIGINT,
HOUSENUM TEXT,
ADDNUM1 TEXT,
ADDNUM2 TEXT,
HOUSETYPE BIGINT,
ADDTYPE1 BIGINT,
ADDTYPE2 BIGINT,
OPERTYPEID BIGINT,
PREVID BIGINT,
NEXTID BIGINT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTUAL BIGINT,
ISACTIVE BIGINT
)
PARTITION BY LIST (REGION);

/*CREATE UNIQUE INDEX HOUSES_REGION_ID_ux
ON HOUSES (REGION,ID);*/