CREATE TABLE IF NOT EXISTS OPERATIONTYPES
(
ID BIGINT,
NAME TEXT,
SHORTNAME TEXT,
DESCR TEXT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
ISACTIVE BIGINT
);

/*CREATE UNIQUE INDEX OPERATIONTYPES_ID_ux
ON OPERATIONTYPES (ID);*/