CREATE TABLE IF NOT EXISTS APARTMENTS_PARAMS<?= $suffix ?>
(
REGION BIGINT,
ID BIGINT,
OBJECTID BIGINT,
CHANGEID BIGINT,
CHANGEIDEND BIGINT,
TYPEID BIGINT,
VALUE TEXT,
UPDATEDATE DATE,
STARTDATE DATE,
ENDDATE DATE
);

/*CREATE UNIQUE INDEX APARTMENTS_PARAMS<?= $suffix ?>_REGION_ID_ux
ON APARTMENTS_PARAMS<?= $suffix ?> (REGION,ID);*/

ALTER TABLE APARTMENTS_PARAMS
ATTACH PARTITION APARTMENTS_PARAMS<?= $suffix ?> FOR
VALUES IN (<?= $suffix ?>);